# Atividades Básicas 1

**Nome: Leonardo Yves de Souza Melo**<br>
**Email: `leoyves@matematica.ufrj.br`**<br>
**Telefone: 21978770025**

In [171]:
# Implementar no terminal
# pip install torch torchvision torchaudio

In [172]:
import torch

# 1. Introdução ao PyTorch

Soma entre $\vec{a} = (1, 2, 3)$ e $\vec{b} = (4, 5, 6)$.

$\vec{a} = (1,2,3) :=:$ `torch.tensor([1.0,2.0,3.0])`

In [173]:
# Verificação de parâmetros básicos da biblioteca
## Versão
print(f"Versão do PyTorch: {torch.__version__}")
## Disponibilidade da GPU
print(f"GPU disponível: {torch.cuda.is_available()}")

# Verficação do nome da GPU
if torch.cuda.is_available():
  print(f"Nome da GPU: {torch.cuda.get_device_name(0)}")

Versão do PyTorch: 2.5.1+cu121
GPU disponível: False


In [174]:
# Criando dois tensores no PyTorch
## a \in R^3
## b \in R^3
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])


# Operações Básicas
## Soma
c = a + b
print(f"Resultado da soma: {c}")
## Subtração
d = a - b
print(f"Resultado da subtração: {d}")
## Multiplicação
e = a * b
print(f"Resultado da multiplicação: {e}")
## Divisão
f = a / b
print(f"Resultado da divisão: {f}")

# Enviando o tensor para a GPU (se disponível)
if torch.cuda.is_available():
  a = a.to_cuda("cuda")
  b = b.to_cuda("cuda")
  c = a + b
  print(f"Resultado da soma na GPU: {c}")

Resultado da soma: tensor([5., 7., 9.])
Resultado da subtração: tensor([-3., -3., -3.])
Resultado da multiplicação: tensor([ 4., 10., 18.])
Resultado da divisão: tensor([0.2500, 0.4000, 0.5000])


# 2. Trabalhando com tensores

In [175]:
import numpy as np

In [176]:
# Criação de tensor a partir de um escalar
## Número real
escalar = 3.14
tensor_escalar = torch.tensor(escalar)
print(f"Tensor criado a partir de um escalar: {tensor_escalar}\n")

# Criação de tensor a partir de uma lista
## Vetor do R^5
lista  = [1, 2, 3, 4, 5]
tensor_lista = torch.tensor(lista)
print(f"Tensor criado a partir de uma lista: {tensor_lista}\n")

# Criação de tensor a partir de um numpy.ndarray
## Vetor do R^5
array = np.array([1, 2, 3, 4, 5])
tensor_array = torch.tensor(array)
print(f"Tensor criado a partir de um array: {tensor_array}")

Tensor criado a partir de um escalar: 3.140000104904175

Tensor criado a partir de uma lista: tensor([1, 2, 3, 4, 5])

Tensor criado a partir de um array: tensor([1, 2, 3, 4, 5])


In [177]:
# Tensor de zeros
## Matriz de 2 linhas e 3 colunas
tensor_zeros = torch.zeros((2,3))
print(f"Tensor de zeros: \n{tensor_zeros}\n")

# Tensor de uns
## Matriz de 3 linhas e 3 colunas
tensor_uns = torch.ones((3,3))
print(f"Tensor de uns: \n{tensor_uns}\n")

# Tensor de valores aleatórios
## As entradas são Unif((0,1]) independentes
## Matriz de 2 linhas e 4 colunas
tensor_random = torch.rand((2,4))
print(f"Tensor com valores aleatórios:\n{tensor_random}\n")

Tensor de zeros: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Tensor de uns: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Tensor com valores aleatórios:
tensor([[0.2067, 0.1413, 0.7471, 0.1610],
        [0.9806, 0.7361, 0.2264, 0.8430]])



In [178]:
# Criando um tensor 2d a partir do range (built-in) e matriz numpy
lista_1d = range(1,10)
lista_2d = np.array(lista_1d).reshape(3,3)
tensor_2d = torch.tensor(lista_2d)
print(f"Tensor 2D:\n{tensor_2d}\n")

# Selecionar uma linha
linha = tensor_2d[1]
print(f"Linha 1: {linha}\n")

# Selecionar um elemento específico
elemento = tensor_2d[2,1]
print(f"Elemento [2,1]: {elemento}\n")

# Selecionar uma coluna
coluna = tensor_2d[:,2]
print(f"Coluna 2: {coluna}")

Tensor 2D:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Linha 1: tensor([4, 5, 6])

Elemento [2,1]: 8

Coluna 2: tensor([3, 6, 9])


In [179]:
# Criando um tensor a partir do range do PyTorch
## Vetor do R^9
tensor_reshaping = torch.arange(1, 10)
print(f"Tensor original: {tensor_reshaping}\n")

# Reshape para 3x3
## Matriz 2D do PyTorch
tensor_reshaped = tensor_reshaping.view(3,3)
print(f"Tensor reshaped (3x3):\n{tensor_reshaped}\n")

# Flatten (1D)
## Transforma o tensor em um vetor 1D e volta para o estado anterior
## Método inplace
tensor_flatten = tensor_reshaped.flatten()
print(f"Tensor flatten: {tensor_flatten}")

Tensor original: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

Tensor reshaped (3x3):
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Tensor flatten: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


Criando o tensor $(0,\frac{\pi}{4}, \frac{\pi}{2})$

In [180]:
# Funções Trigonométricas
tensor = torch.tensor([0.0, torch.pi/4, torch.pi/2])

seno = torch.sin(tensor)
print(f"Seno: {seno}\n")

cosseno = torch.cos(tensor)
print(f"Cosseno: {cosseno}\n")

tangente = torch.tan(tensor)
print(f"Tangente: {tangente}\n\n")

# Função Exponencial e Logarítmica
tensor = torch.tensor([1.0, 2.0, 3.0])

exponencial = torch.exp(tensor)
print(f"Exponencial: {exponencial}\n")

logaritmo = torch.log(tensor)
print(f"Logarítmico: {logaritmo}")

Seno: tensor([0.0000, 0.7071, 1.0000])

Cosseno: tensor([ 1.0000e+00,  7.0711e-01, -4.3711e-08])

Tangente: tensor([ 0.0000e+00,  1.0000e+00, -2.2877e+07])


Exponencial: tensor([ 2.7183,  7.3891, 20.0855])

Logarítmico: tensor([0.0000, 0.6931, 1.0986])


In [181]:
tensor = torch.arange(1,10).view(3,3)
print(f"Tensor: \n{tensor}\n")

# Soma de todas as entradas
soma = torch.sum(tensor)
print(f"Soma total: {soma}\n")

# Produto de todas as entradas
prod = torch.prod(tensor)
print(f"Produto total: {prod}\n")

# Média
media = torch.mean(tensor.float())
print(f"Média: {media}\n")

# Desvio Padrão
desv_pad = torch.std(tensor.float())
print(f"Desvio Padrão: {desv_pad}\n")

# Variância
variance = torch.var(tensor.float())
print(f"Variância: {variance}\n")

# Máximo
maximo = torch.max(tensor)
print(f"Máximo: {maximo}\n")

# Índice do máximo
max_index = torch.argmax(tensor)
print(f"Índice do máximo: {max_index}")

Tensor: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Soma total: 45

Produto total: 362880

Média: 5.0

Desvio Padrão: 2.7386128902435303

Variância: 7.5

Máximo: 9

Índice do máximo: 8


In [182]:
matriz_a = torch.arange(1,5).view(2,2)
matriz_b = torch.arange(5,9).view(2,2)
print(f"Matriz A:\n{matriz_a}\n")
print(f"Matriz B:\n{matriz_b}\n")

# Multiplicação Matricial
produto_matricial=  torch.matmul(matriz_a, matriz_b)
print(f"Produto matricial:\n{produto_matricial}\n")

# Determinante
# Necessário transformar em float
determinante = torch.linalg.det(matriz_a.float())
print(f"Determinante: {determinante}")

Matriz A:
tensor([[1, 2],
        [3, 4]])

Matriz B:
tensor([[5, 6],
        [7, 8]])

Produto matricial:
tensor([[19, 22],
        [43, 50]])

Determinante: -2.0


## 2.1 Mais operações com tensores

In [183]:
tensor1 = torch.arange(1,5).view(2,2)
print(f"Tensor 1:\n{tensor1}\n")
tensor2 = torch.arange(5,9).view(2,2)
print(f"Tensor 2:\n{tensor2}\n")

# Concatenando tensores
## Concatenando ao longo da dimensão 0, empilhamento vertical de tensores,
## o tensor passa de 2x2 para 4x2
concat_dim0 = torch.cat((tensor1, tensor2), dim=0)
print(f"Concatenação ao longo da dimensão 0: \n{concat_dim0}\n")

## Concatenando ao longo da dimensão 1, empilhamento horizontal de tensores,
## o tensor passa de 2x2 para 2x4
concat_dim1 = torch.cat((tensor1, tensor2), dim=1)
print(f"Concatenação do longo da dimensão 1: \n{concat_dim1}\n\n")

Tensor 1:
tensor([[1, 2],
        [3, 4]])

Tensor 2:
tensor([[5, 6],
        [7, 8]])

Concatenação ao longo da dimensão 0: 
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

Concatenação do longo da dimensão 1: 
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])




In [184]:
tensor1 = torch.arange(1,5).view(2,2)
tensor2 = torch.arange(5,9).view(2,2)

# Stacking (adiciona nova dimensão)
## Dimensão 0
stacked0 = torch.stack((tensor1, tensor2), dim=0)
print(f"Stacking na dimensão 0:\n{stacked0}\n",
      f"Dimensão: {stacked0.size()}\n")
## Dimensão 1
stacked1 = torch.stack((tensor1, tensor2), dim=1)
print(f"Stacking na dimensão 1:\n{stacked1}\n",
      f"Dimensão: {stacked1.size()}")

Stacking na dimensão 0:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
 Dimensão: torch.Size([2, 2, 2])

Stacking na dimensão 1:
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])
 Dimensão: torch.Size([2, 2, 2])


In [185]:
tensor1 = torch.arange(1,5).view(2,2)

# Split
## Cada uma das entradas do tensor se torna um tensor escalar
split_tensors = torch.chunk(tensor1, chunks=2, dim=1)
print(f"Split: {split_tensors}\n Tipo: {split_tensors.__class__}\n")

# Transposição
transposed = tensor1.T
print(f"Transposição: \n{transposed}\n\n",
      f"Shape antigo: {tensor1.size()}\n",
      f"Shape novo: {transposed.size()}")

Split: (tensor([[1],
        [3]]), tensor([[2],
        [4]]))
 Tipo: <class 'tuple'>

Transposição: 
tensor([[1, 3],
        [2, 4]])

 Shape antigo: torch.Size([2, 2])
 Shape novo: torch.Size([2, 2])


In [186]:
# Tensor 4x4
tensor = torch.arange(1,17).reshape(4,4)
print(f"Tensor:\n{tensor}\n")

# Slicing
## Seleção das linhas 1 e 2
## Seleção das colunas 1 e 2
## O tensor resultante é 2x2
sub_tensor = tensor[1:3, 1:3]
print(f"Tensor resultante:\n{sub_tensor}\n",
      f"Shape: {sub_tensor.size()}")

# Indexação Booleana
## Seleção dos elementos maiores que 10, fazendo o reshaping necessário
boolean_tensor = tensor[tensor > 10]
print(f"\nIndexação Booleana: {boolean_tensor}")

# Máscara
## Seleção apenas de elementos pares, fazendo o reshaping necessário
mask = tensor % 2 == 0
masked_tensor = tensor[mask]
print(f"\nMáscara: {masked_tensor}")

Tensor:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

Tensor resultante:
tensor([[ 6,  7],
        [10, 11]])
 Shape: torch.Size([2, 2])

Indexação Booleana: tensor([11, 12, 13, 14, 15, 16])

Máscara: tensor([ 2,  4,  6,  8, 10, 12, 14, 16])


In [187]:
# O tensor abaixo é equivalente a um par ordenado de matrizes 3x4
tensor = torch.arange(1,25).reshape(2,3,4)

# Permutação de dimensões, o tensor resultante
# é uma quádrupla ordenada de matriz 3x2
## permuted[D] = tensor[:,:,D].T, D \in {0,1,2,3}
permuted = tensor.permute(2,1,0)
print(f"Tensor com dimensões permutadas:\n{permuted}")

Tensor com dimensões permutadas:
tensor([[[ 1, 13],
         [ 5, 17],
         [ 9, 21]],

        [[ 2, 14],
         [ 6, 18],
         [10, 22]],

        [[ 3, 15],
         [ 7, 19],
         [11, 23]],

        [[ 4, 16],
         [ 8, 20],
         [12, 24]]])


estudar contiguidade...

`view(), reshape(), flatten(), transpose()`

In [188]:
# Matriz 3x4
tensor = torch.arange(1,13).reshape(3,4)
print(f"Tensor:\n{tensor}")

# Soma ao longo da dimensão 0
## Soma ao longo das colunas da matriz
sum_dim0 = tensor.sum(dim=0)
print(f"\nSoma ao longo da dimensão 0: {sum_dim0}")

# Soma ao longo da dimensão 1
## Soma ao longo das linhas da matriz
sum_dim1 = tensor.sum(dim=1)
print(f"\nSoma ao longo da dimensão 1: {sum_dim1}")

# Média ao longo da dimensão 1
mean_dim1 = tensor.float().mean(dim=1)
print(f"\nMédia ao longo da dimensão 1: {mean_dim1}")

# Desvio Padrão ao longo da dimensão 1
std_dim1 = tensor.float().std(dim=1)
print(f"\nDesvio Padrão ao longo da dimensão 1: {std_dim1}\n")

# Variância ao longo da dimensão 1
var_dim1 = tensor.float().var(dim=1)
print(f"Vaiância ao longo da dimensão 1: {var_dim1}")


Tensor:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Soma ao longo da dimensão 0: tensor([15, 18, 21, 24])

Soma ao longo da dimensão 1: tensor([10, 26, 42])

Média ao longo da dimensão 1: tensor([ 2.5000,  6.5000, 10.5000])

Desvio Padrão ao longo da dimensão 1: tensor([1.2910, 1.2910, 1.2910])

Vaiância ao longo da dimensão 1: tensor([1.6667, 1.6667, 1.6667])


## 2.2 Métodos de inspeção em tensores

In [189]:
# Matriz 2x3
tensor1 = torch.arange(1,7).reshape(2,3)
## Inspeção das dimensões
print("Shape do tensor1:", tensor1.shape)
print("Size do tensor1:", tensor1.size())

# Tripla ordenada de matrizes 4x5, com entradas independentes
# oriundas de N(0,1)
tensor2 = torch.randn(3,4,5)
## Inspeção das dimensões
print("\nShape do tensor2:", tensor2.shape)
print("Size do tensor2:", tensor2.size())

# Vetor do R^10 em que todas as entradas são iguais a 1
tensor3 = torch.ones(10)
## Inspeção das dimensões
print("\nShape do tensor3:", tensor3.shape)
print("Size do tensor3:", tensor3.size())

Shape do tensor1: torch.Size([2, 3])
Size do tensor1: torch.Size([2, 3])

Shape do tensor2: torch.Size([3, 4, 5])
Size do tensor2: torch.Size([3, 4, 5])

Shape do tensor3: torch.Size([10])
Size do tensor3: torch.Size([10])


In [190]:
# Tripla ordenada de matrizes 4x5
tensor = torch.randn(3,4,5)

# Acessando dimenões específicas
dim0 = tensor.shape[0]
print(f"Dimensão 0 (tamanho): {dim0}")

dim1 = tensor.size(1)
print(f"\nDimensão 1 (tamanho): {dim1}")

dim2 = tensor.shape[2]
print(f"\nDimensão 2 (tamanho): {dim2}")

Dimensão 0 (tamanho): 3

Dimensão 1 (tamanho): 4

Dimensão 2 (tamanho): 5


In [191]:
# Matriz 2x3 com todos os elmentos iguais a zero
tensor1 = torch.zeros(2,3)
# Quadrupla ordenada de matrizes 5x6 com todos os elementos iguais a um
tensor2 = torch.ones(4,5,6)
# Vetor do R^10 com todos os elementos aleatórios
tensor3 = torch.randn(10)

# Calculando o número total de elementos
numel1 = tensor1.numel()
print(f"Número total de elementos no tensor1: {numel1}")

numel2 = tensor2.numel()
print(f"Número total de elementos no tensor2: {numel2}")

numel3 = tensor3.numel()
print(f"Número total de elementos no tensor3: {numel3}")


Número total de elementos no tensor1: 6
Número total de elementos no tensor2: 120
Número total de elementos no tensor3: 10


## 2.3 Bônus: conversão e manipulação de tensores

In [192]:
# Tensor escalar
scalar_tensor = torch.tensor([42.0])
value = scalar_tensor.item()
print(f"Valor extraído: {value}")

# Tensor com mais de um elemento
tensor_multi = torch.tensor([1.0,2.0,3.0])
try:
  print(tensor_multi.item())
except RuntimeError as e:
  print(f"Erro capturado: {e}")

# Solução
value = tensor_multi[0].item()
print(f"Valor extraído do primeiro elemento: {value}")

Valor extraído: 42.0
Erro capturado: a Tensor with 3 elements cannot be converted to Scalar
Valor extraído do primeiro elemento: 1.0


In [193]:
tensor = torch.arange(16)

# Vetor do R^16
tensor1d = tensor
list_value1d = tensor1d.tolist()
print(f"tensor1d: {tensor1d}")
print(f"tensor1d convertido em lista: {list_value1d}\n")

# Matriz 4x4
tensor2d = tensor.reshape(4,4)
list_value2d = tensor2d.tolist()
print(f"tensor2d:\n{tensor2d}")
print(f"tensor2d convertido em lista: {list_value2d}\n")

# Par ordenado de matrizes 4x2
tensor3d = tensor.reshape(2,4,2)
list_value3d = tensor3d.tolist()
print(f"tensor3d:\n{tensor3d}")
print(f"tensor3d convertido em lista: {list_value3d}\n")

tensor1d: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
tensor1d convertido em lista: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

tensor2d:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor2d convertido em lista: [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]

tensor3d:
tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]])
tensor3d convertido em lista: [[[0, 1], [2, 3], [4, 5], [6, 7]], [[8, 9], [10, 11], [12, 13], [14, 15]]]



In [194]:
tensor = torch.arange(6).reshape(2,3)
print(f"Tensor:\n{tensor}\n",
      f"Tipo: {tensor.__class__}\n")

# Transformação de tensor em numpy array
numpy_array = tensor.numpy()
print(f"Numpy Array: \n{numpy_array}\n",
      f"Tipo: {numpy_array.__class__}")

# Modificar o array NumPy e observar o tensor original
numpy_array[0, 0] = 99
print(f"\nTensor original após modificar o NumPy:\n{tensor}")

Tensor:
tensor([[0, 1, 2],
        [3, 4, 5]])
 Tipo: <class 'torch.Tensor'>

Numpy Array: 
[[0 1 2]
 [3 4 5]]
 Tipo: <class 'numpy.ndarray'>

Tensor original após modificar o NumPy:
tensor([[99,  1,  2],
        [ 3,  4,  5]])
